[LinkedIn](https://www.linkedin.com/posts/mythilyramanathan_day1-activity-7142990614387687425-K_Nu?utm_source=share&utm_medium=member_desktop)

Problem: 
Amber's conglomerate corporation just acquired some new companies. Each of the companies follows this hierarchy:

Given the table schemas , write a query to print the company_code, founder name, the total number of lead managers, the total number of senior managers, the total number of managers, and the total number of employees. Order your output by ascending company_code.

Solution: In the pdf attached in LinkenIn Post.

Used joins, group by, and order by
